<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <FileVersion>0.1.0.0</FileVersion>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <Version>0.1</Version>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>Wolfenshine</AssemblyName>
    <RootNamespace>Wolfenshine</RootNamespace>
    <ApplicationIcon>Assets/Wolfenshine.ico</ApplicationIcon>
    <Authors>Dean Edis</Authors>
    <Company>Dean Edis (DeanTheCoder)</Company>
    <Copyright>Copyright (c) 2026 Dean Edis</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.3" />
    <PackageReference Include="NukedOPL3Sharp" Version="1.2.1" />
    <PackageReference Include="OpenTK.Audio.OpenAL" Version="4.8.2" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.1.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DTC.Core/DTC.Core/DTC.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>

  <ItemGroup>
    <LocalWolfensteinFullData Include="$(MSBuildProjectDirectory)/../local/game-data/*.WL6" />
    <LocalWolfensteinSharewareData Include="$(MSBuildProjectDirectory)/../local/game-data/*.WL1" />
    <LocalWolfensteinSharewareArchive Include="$(MSBuildProjectDirectory)/../local/game-data/w3d-box.zip"
                                      Condition="Exists('$(MSBuildProjectDirectory)/../local/game-data/w3d-box.zip')" />
  </ItemGroup>

  <Target Name="CopyLocalWolfensteinData" AfterTargets="Build"
          Condition="'@(LocalWolfensteinFullData)' != '' or '@(LocalWolfensteinSharewareData)' != '' or '@(LocalWolfensteinSharewareArchive)' != ''">
    <MakeDir Directories="$(TargetDir)GameData" />
    <Unzip SourceFiles="@(LocalWolfensteinSharewareArchive)"
           DestinationFolder="$(IntermediateOutputPath)WolfensteinShareware"
           SkipUnchangedFiles="true"
           Condition="'@(LocalWolfensteinFullData)' == '' and '@(LocalWolfensteinSharewareData)' == '' and '@(LocalWolfensteinSharewareArchive)' != ''" />
    <ItemGroup>
      <ExtractedWolfensteinSharewareData Include="$(IntermediateOutputPath)WolfensteinShareware/WOLF3D/AUDIOHED.WL1;
                                                   $(IntermediateOutputPath)WolfensteinShareware/WOLF3D/AUDIOT.WL1;
                                                   $(IntermediateOutputPath)WolfensteinShareware/WOLF3D/GAMEMAPS.WL1;
                                                   $(IntermediateOutputPath)WolfensteinShareware/WOLF3D/MAPHEAD.WL1;
                                                   $(IntermediateOutputPath)WolfensteinShareware/WOLF3D/VGADICT.WL1;
                                                   $(IntermediateOutputPath)WolfensteinShareware/WOLF3D/VGAGRAPH.WL1;
                                                   $(IntermediateOutputPath)WolfensteinShareware/WOLF3D/VGAHEAD.WL1;
                                                   $(IntermediateOutputPath)WolfensteinShareware/WOLF3D/VSWAP.WL1"
                                         Condition="'@(LocalWolfensteinFullData)' == '' and '@(LocalWolfensteinSharewareData)' == ''" />
      <ExistingWolfensteinFullOutput Include="$(TargetDir)GameData/*.WL6" />
      <ExistingWolfensteinSharewareOutput Include="$(TargetDir)GameData/*.WL1" />
      <ObsoleteWolfensteinPaletteOutput Include="$(TargetDir)GameData/GAMEPAL.OBJ" />
      <UnneededWolfensteinConfigOutput Include="$(TargetDir)GameData/CONFIG.WL1" />
    </ItemGroup>
    <Delete Files="@(ObsoleteWolfensteinPaletteOutput)" />
    <Delete Files="@(UnneededWolfensteinConfigOutput)" />
    <Delete Files="@(ExistingWolfensteinSharewareOutput)"
            Condition="'@(LocalWolfensteinFullData)' != ''" />
    <Delete Files="@(ExistingWolfensteinFullOutput)"
            Condition="'@(LocalWolfensteinFullData)' == '' and ('@(LocalWolfensteinSharewareData)' != '' or '@(ExtractedWolfensteinSharewareData)' != '')" />
    <Copy SourceFiles="@(LocalWolfensteinFullData)"
          DestinationFolder="$(TargetDir)GameData"
          SkipUnchangedFiles="true"
          Condition="'@(LocalWolfensteinFullData)' != ''" />
    <Copy SourceFiles="@(LocalWolfensteinSharewareData)"
          DestinationFolder="$(TargetDir)GameData"
          SkipUnchangedFiles="true"
          Condition="'@(LocalWolfensteinFullData)' == '' and '@(LocalWolfensteinSharewareData)' != ''" />
    <Copy SourceFiles="@(ExtractedWolfensteinSharewareData)"
          DestinationFolder="$(TargetDir)GameData"
          SkipUnchangedFiles="true"
          Condition="'@(LocalWolfensteinFullData)' == '' and '@(LocalWolfensteinSharewareData)' == '' and '@(ExtractedWolfensteinSharewareData)' != ''" />
  </Target>
</Project>
